import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="vi" suppressHydrationWarning className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <div className="min-h-screen paper-grid">{children}</div>
      </body>
    </html>
  );
}
