/* Nhai HSK clone — shared shell (navbar, login modal, settings, floating, helpers).
   Do NOT edit this file from feature agents. */
(function () {
  "use strict";
  window.NHAI = window.NHAI || {};

  /* ---------- helpers ---------- */
  NHAI.q = function (name, def) {
    var m = new URLSearchParams(location.search).get(name);
    return m === null || m === "" ? (def === undefined ? null : def) : m;
  };
  NHAI.el = function (html) {
    var t = document.createElement("template");
    t.innerHTML = html.trim();
    return t.content.firstElementChild;
  };
  var toastTimer = null;
  NHAI.toast = function (msg) {
    var old = document.querySelector(".toast");
    if (old) old.remove();
    var t = NHAI.el('<div class="toast">' + msg + "</div>");
    document.body.appendChild(t);
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { t.remove(); }, 2600);
  };
  NHAI.speak = function (text, lang, rate) {
    try {
      if (!("speechSynthesis" in window)) return;
      speechSynthesis.cancel();
      var u = new SpeechSynthesisUtterance(text);
      u.lang = lang || "zh-CN";
      u.rate = rate || 1;
      var voicePref = localStorage.getItem("nhai.voice") || "female";
      var voices = speechSynthesis.getVoices().filter(function (v) { return /^zh/i.test(v.lang); });
      var pick = voices.find(function (v) { return (voicePref === "male" ? /male|daniel|tington/i : /female|mei|tingting|hui/i).test(v.name); }) || voices[0];
      if (pick) u.voice = pick;
      speechSynthesis.speak(u);
    } catch (e) { /* silent */ }
  };
  NHAI.stripTones = function (s) {
    return String(s).toLowerCase()
      .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      .replace(/ü/g, "v").replace(/[:' ’·]/g, "");
  };
  NHAI.isLoggedIn = function () { return localStorage.getItem("nhai.mockLogin") === "1"; };

  /* ---------- nav data ---------- */
  var NAV = [
    { name: "Nền tảng", items: [
      { label: "Bảng Pinyin", href: "pinyin.html" },
      { label: "214 Bộ Thủ", href: "radicals.html" },
      { label: "Quy tắc chuyển âm", href: "sound-rules.html" }
    ]},
    { name: "Cá nhân hoá", items: [
      { label: "Lộ trình", href: "roadmap.html" },
      { label: "Ôn tập", href: "review.html" },
      { label: "Sổ tay từ vựng", href: "my-vocab.html" },
      { label: "Sổ tay ngữ pháp", href: "my-grammar.html" },
      { label: "Tiến độ học", href: "progress.html" }
    ]},
    { name: "Tra từ điển", items: [
      { label: "Tra từ điển", href: "dictionary.html" },
      { label: "Phân tích Hán tự", href: "hanzi.html" }
    ]},
    { name: "Cộng đồng", items: [
      { label: "Nhóm Facebook", href: "https://www.facebook.com/groups/nhaihsk" },
      { label: "Học tiếng Nhật", href: "https://nhaikanji.com" },
      { label: "Học tiếng Hàn", href: "https://nhaitopik.com" }
    ]}
  ];
  var DIRECT = [
    { label: "Shadowing", href: "shadowing.html" },
    { label: "Bài khoá", href: "reading.html" },
    { label: "Luyện thi chứng chỉ", href: "certificate-test.html" },
    { label: "Tạo file", href: "create-file.html" },
    { label: "Bảng xếp hạng", href: "leaderboard.html" },
    { label: "Góp ý", href: "feedback.html" }
  ];
  var ALL_LINKS = [];
  NAV.forEach(function (g) { ALL_LINKS = ALL_LINKS.concat(g.items.map(function (i) { return { group: g.name, label: i.label, href: i.href }; })); });
  ALL_LINKS = ALL_LINKS.concat(DIRECT);

  function isExternal(href) { return /^https?:/.test(href); }

  /* ---------- sidebar data (SPEC-10) ---------- */
  var SIDEBAR = [
    { label: "Trang chủ", icon: "🏠", href: "index.html", match: ["index.html"] },
    { label: "Nền tảng", icon: "📚", group: 0, match: ["pinyin.html", "radicals.html", "sound-rules.html", "pinyin-practice.html"] },
    { label: "Cá nhân hoá", icon: "🎯", group: 1, match: ["roadmap.html", "roadmap-pinyin.html", "review.html", "my-vocab.html", "my-grammar.html", "progress.html"] },
    { label: "Tra từ điển", icon: "🔍", group: 2, match: ["dictionary.html", "hanzi.html"] },
    { label: "Shadowing", icon: "🎧", href: "shadowing.html", match: ["shadowing.html", "shadowing-video.html"] },
    { label: "Bài khoá", icon: "📖", href: "reading.html", match: ["reading.html"] },
    { label: "Luyện thi chứng chỉ", icon: "📝", href: "certificate-test.html", match: ["certificate-test.html"] },
    { label: "Tạo file", icon: "🖨️", href: "create-file.html", match: ["create-file.html"] },
    { label: "Cài đặt", icon: "⚙️", action: "settings" }
  ];

  function currentPage() {
    var f = location.pathname.split("/").pop();
    return f === "" ? "index.html" : f;
  }
  function isSidebarActive(it) {
    var f = currentPage();
    return (it.match || []).indexOf(f) >= 0;
  }
  function closeSidePanels() {
    document.querySelectorAll("[data-side-panel], [data-top-panel]").forEach(function (p) { p.remove(); });
    document.querySelectorAll("[data-side-group]").forEach(function (b) { b.setAttribute("aria-expanded", "false"); });
  }

  function renderSidebar(host) {
    var sb = document.createElement("aside");
    sb.setAttribute("data-sidebar", "");
    sb.className = "hidden lg:flex fixed left-0 top-0 h-full w-[72px] z-[400] flex-col items-center gap-1 py-3 bg-[var(--nhai-card)] border-r-2 border-[var(--nhai-border)] overflow-y-auto";

    var html =
      '<a href="index.html" class="flex flex-col items-center gap-1 mb-2 shrink-0" title="Nhai HSK — Trang chủ">' +
        '<span class="w-9 h-9 rounded-md bg-[var(--nhai-main)] text-white flex items-center justify-center text-lg font-extrabold zh">奈</span>' +
        '<span class="text-[10px] font-extrabold tracking-tight">Nhai<span class="text-[var(--nhai-main)]">HSK</span></span>' +
      "</a>";
    SIDEBAR.forEach(function (it, si) {
      var active = isSidebarActive(it);
      var cls = "w-14 py-1.5 rounded-lg border-2 flex flex-col items-center gap-0.5 text-[10px] font-semibold leading-tight text-center " +
        (active
          ? "bg-[var(--nhai-soft)] border-[var(--nhai-border)] text-[var(--nhai-main)]"
          : "border-transparent text-[var(--nhai-muted)] hover:text-[var(--nhai-main)] hover:border-[var(--nhai-border)]");
      if (it.action === "settings") {
        html += '<button type="button" data-side-settings class="' + cls + '"><span class="text-lg" aria-hidden="true">' + it.icon + '</span><span>' + it.label + "</span></button>";
      } else if (it.group !== undefined) {
        html += '<button type="button" data-side-group="' + it.group + '" aria-expanded="false" class="' + cls + '">' +
          '<span class="text-lg" aria-hidden="true">' + it.icon + "</span><span>" + it.label + " ›</span></button>";
      } else {
        html += '<a href="' + it.href + '" class="' + cls + '">' +
          '<span class="text-lg" aria-hidden="true">' + it.icon + "</span><span>" + it.label + "</span></a>";
      }
    });
    sb.innerHTML = html;
    document.body.insertBefore(sb, document.body.firstChild);

    /* submenu popover: position fixed, mở bằng click, đóng outside/Escape */
    sb.querySelectorAll("[data-side-group]").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.stopPropagation();
        var gi = btn.getAttribute("data-side-group");
        var existing = document.querySelector('[data-side-panel="' + gi + '"]');
        var wasOpen = !!existing;
        closeSidePanels();
        if (wasOpen) return;
        var g = NAV[parseInt(gi, 10)];
        var links = "";
        g.items.forEach(function (item) {
          var ext = isExternal(item.href) ? ' target="_blank" rel="noopener"' : "";
          var on = item.href === currentPage() ? " bg-[var(--nhai-soft)] text-[var(--nhai-main)]" : "";
          var badge = item.label === "Bảng Pinyin" ? '<span class="absolute -top-1 -right-2 border-2 border-[#c03922] bg-[var(--nhai-card)] rounded-full px-1 text-[9px] font-bold leading-tight text-[#c03922]">học kỹ ×99</span>' : "";
          links += '<a href="' + item.href + '"' + ext + ' class="relative block px-3 py-2 rounded-md text-sm font-medium hover:bg-[var(--nhai-soft)] whitespace-nowrap' + on + '">' + item.label + badge + "</a>";
        });
        var r = btn.getBoundingClientRect();
        var panel = NHAI.el('<div data-side-panel="' + gi + '" class="hidden card shadow-neo p-1 z-[500] fixed w-52" style="left:76px;top:' + Math.max(8, r.top - 4) + 'px">' + links + "</div>");
        panel.classList.remove("hidden");
        document.body.appendChild(panel);
        /* clamp: không tràn đáy viewport */
        var maxTop = window.innerHeight - panel.offsetHeight - 8;
        panel.style.top = Math.max(8, Math.min(r.top - 4, maxTop)) + "px";
        btn.setAttribute("aria-expanded", "true");
      });
    });
    sb.querySelectorAll("[data-side-settings]").forEach(function (btn) {
      btn.addEventListener("click", toggleSettings);
    });
    document.addEventListener("click", function (e) {
      if (!e.target.closest || (!e.target.closest("[data-side-panel]") && !e.target.closest("[data-side-group]") &&
          !e.target.closest("[data-top-panel]") && !e.target.closest("[data-bell]"))) closeSidePanels();
    });
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") closeSidePanels();
    });
  }

  function renderShell() {
    var host = document.querySelector("[data-shell]");
    if (!host) return;

    /* desktop: fixed sidebar 72px + body padding-left 72px (không move DOM) */
    if (!document.getElementById("nhai-shell-style")) {
      var st = document.createElement("style");
      st.id = "nhai-shell-style";
      st.textContent = "@media (min-width:1024px){body{padding-left:72px}}";
      document.head.appendChild(st);
    }
    document.body.classList.add("paper-grid");
    renderSidebar(host);

    var nav = '<nav class="hidden md:flex items-center gap-1" data-nav-group>';
    NAV.forEach(function (g, gi) {
      nav += '<div class="relative"><button type="button" data-menu="' + gi + '" class="btn-ghost px-3 py-2 text-sm">' + g.name + " ▾</button>" +
        '<div class="hidden absolute left-0 mt-1 w-52 card shadow-neo p-1 z-[500]" data-menu-panel="' + gi + '">';
      g.items.forEach(function (it) {
        var ext = isExternal(it.href) ? ' target="_blank" rel="noopener"' : "";
        nav += '<a href="' + it.href + '"' + ext + ' class="block px-3 py-2 rounded-md text-sm font-medium hover:bg-[var(--nhai-soft)]">' + it.label + "</a>";
      });
      nav += "</div></div>";
    });
    DIRECT.forEach(function (d) {
      nav += '<a href="' + d.href + '" class="px-3 py-2 text-sm font-semibold rounded-md hover:text-[var(--nhai-main)]">' + d.label + "</a>";
    });
    nav += "</nav>";

    var mobileLinks = "";
    ALL_LINKS.forEach(function (l) {
      var badge = l.label === "Bảng Pinyin" ? '<span class="absolute -top-1 -right-2 border-2 border-[#c03922] bg-[var(--nhai-card)] rounded-full px-1 text-[9px] font-bold leading-tight text-[#c03922]">học kỹ ×99</span>' : "";
      mobileLinks += '<a href="' + l.href + '" class="relative block px-4 py-2 text-sm font-medium border-b border-[var(--nhai-border)]">' + (l.group ? l.group + " · " : "") + l.label + badge + "</a>";
    });

    host.innerHTML =
      /* topbar desktop (trong vùng content, bên phải sidebar) */
      '<div class="hidden lg:flex items-center gap-3 px-6 py-3 border-b-2 border-[var(--nhai-border)] bg-[var(--nhai-card)]" data-topbar>' +
        '<a href="index.html" class="flex items-center gap-2 text-xl font-extrabold tracking-tight">' +
          '<span class="w-8 h-8 rounded-md bg-[var(--nhai-main)] text-white flex items-center justify-center text-base font-extrabold zh">奈</span>' +
          '<span>Nhai <span class="text-[var(--nhai-main)]">HSK</span></span>' +
        "</a>" +
        '<div class="ml-auto flex items-center gap-2">' +
          '<span data-user class="hidden xl:inline-flex items-center gap-1">' +
            '<span class="text-xs font-semibold text-[var(--nhai-muted)]" title="mỗi câu trả lời đúng +1">⚡ 0 — mỗi câu trả lời đúng +1</span>' +
          "</span>" +
          '<button type="button" data-bell class="btn-ghost w-9 h-9" title="Thông báo">🔔</button>' +
          '<button type="button" data-login class="btn-main px-3 py-2 text-sm">Đăng nhập</button>' +
        "</div>" +
      "</div>" +
      '<div class="border-b-2 border-[var(--nhai-border)] bg-[var(--nhai-card)] lg:hidden">' +
        '<div class="mx-auto max-w-6xl px-4 py-3 flex items-center gap-3">' +
          '<a href="index.html" class="text-xl font-extrabold tracking-tight">Nhai<span class="text-[var(--nhai-main)]">HSK</span></a>' +
          nav +
          '<div class="ml-auto flex items-center gap-2">' +
            '<button type="button" data-menu-mobile class="btn-ghost px-3 py-2 md:hidden">☰ Menu</button>' +
            '<button type="button" data-settings class="btn-ghost px-3 py-2 text-sm">Cài đặt</button>' +
            '<span data-user class="hidden sm:flex items-center gap-2">' +
              '<span class="text-xs font-semibold text-[var(--nhai-muted)]" title="mỗi câu trả lời đúng +1">0 điểm — mỗi câu trả lời đúng +1</span>' +
              '<button type="button" data-login-mobile class="btn-main px-3 py-2 text-sm">Đăng nhập</button>' +
            "</span>" +
          "</div>" +
        "</div>" +
        '<div data-mobile-panel class="hidden border-t-2 border-[var(--nhai-border)] md:hidden">' + mobileLinks + "</div>" +
      "</div>" +
      '<div class="hidden lg:block absolute right-4 top-16 z-[350] text-right text-xs font-semibold leading-snug text-[#c0392b99]">' +
        '<div>HOÀNG SA, TRƯỜNG SA LÀ CỦA VIỆT NAM</div>' +
        '<div class="zh">西沙（黄沙）群岛、南沙（长沙）群岛属于越南</div>' +
      "</div>" +
      '<div class="lg:hidden mx-auto max-w-6xl px-4 pt-3 text-center text-xs font-semibold text-[var(--nhai-muted)]">' +
        '<div>HOÀNG SA, TRƯỜNG SA LÀ CỦA VIỆT NAM</div>' +
        '<div class="zh">西沙（黄沙）群岛、南沙（长沙）群岛属于越南</div>' +
      "</div>";

    /* chuông thông báo (desktop topbar): popup 3 thông báo demo */
    var NOTIFS = [
      { icon: "📘", text: "Bài mới: HSK 1 — Bài 1 Đồ ăn đã mở", href: "reading.html" },
      { icon: "🔔", text: "Nhắc học: hoàn thành 10 từ ôn tập hôm nay", href: "review.html" },
      { icon: "🏆", text: "Bạn đã vào top 10 Bảng xếp hạng XP tuần này", href: "leaderboard.html?tab=xp" }
    ];
    host.querySelector("[data-bell]").addEventListener("click", function (e) {
      e.stopPropagation();
      var existing = document.querySelector("[data-top-panel]");
      closeSidePanels();
      if (existing) return;
      var rows = "";
      NOTIFS.forEach(function (n) {
        rows += '<a href="' + n.href + '" class="block px-3 py-2.5 rounded-md text-sm hover:bg-[var(--nhai-soft)] border-b border-[var(--nhai-border)] last:border-b-0"><span aria-hidden="true">' + n.icon + "</span> " + n.text + "</a>";
      });
      var panel = NHAI.el('<div data-top-panel class="card shadow-neo fixed right-4 top-16 w-80 p-1 z-[500]">' +
        '<div class="px-3 py-2 text-sm font-extrabold border-b-2 border-[var(--nhai-border)] mb-1">Thông báo</div>' + rows + "</div>");
      document.body.appendChild(panel);
    });

    host.querySelector("[data-login]").addEventListener("click", openLogin);

    /* dropdown behavior */
    host.querySelectorAll("[data-menu]").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.stopPropagation();
        var idx = btn.getAttribute("data-menu");
        var panel = host.querySelector('[data-menu-panel="' + idx + '"]');
        var wasOpen = !panel.classList.contains("hidden");
        host.querySelectorAll("[data-menu-panel]").forEach(function (p) { p.classList.add("hidden"); });
        if (!wasOpen) panel.classList.remove("hidden");
      });
    });
    document.addEventListener("click", function (e) {
      if (!e.target.closest || !e.target.closest("[data-nav-group]")) {
        host.querySelectorAll("[data-menu-panel]").forEach(function (p) { p.classList.add("hidden"); });
      }
    });
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") {
        host.querySelectorAll("[data-menu-panel]").forEach(function (p) { p.classList.add("hidden"); });
        closeOverlay();
      }
    });
    host.querySelector("[data-menu-mobile]").addEventListener("click", function () {
      host.querySelector("[data-mobile-panel]").classList.toggle("hidden");
    });

    host.querySelector("[data-login-mobile]").addEventListener("click", openLogin);
    host.querySelector("[data-settings]").addEventListener("click", toggleSettings);
    if (NHAI.isLoggedIn()) renderLoggedIn();
  }

  /* ---------- login modal ---------- */
  function openLogin() {
    closeOverlay();
    var bd = NHAI.el(
      '<div class="modal-backdrop" data-overlay>' +
        '<div class="card shadow-neo w-full max-w-md p-6" role="dialog" aria-label="Đăng nhập">' +
          '<div class="flex items-center justify-between mb-2">' +
            '<h2 class="text-2xl font-extrabold">Đăng nhập</h2>' +
            '<button type="button" data-close class="btn-ghost w-9 h-9">✕</button>' +
          "</div>" +
          '<p class="text-sm text-[var(--nhai-muted)] mb-4">Đăng nhập để đồng bộ tiến trình học của bạn.</p>' +
          '<button type="button" data-provider="google" class="btn-ghost w-full py-2.5 mb-2">🔵 Đăng nhập bằng Google</button>' +
          '<button type="button" data-provider="apple" class="btn-ghost w-full py-2.5 mb-3"> Đăng nhập bằng Apple</button>' +
          '<div class="flex items-center gap-3 my-3 text-xs text-[var(--nhai-muted)]"><span class="flex-1 border-t border-[var(--nhai-border)]"></span>HOẶC<span class="flex-1 border-t border-[var(--nhai-border)]"></span></div>' +
          '<input type="email" placeholder="Email" class="w-full border-2 border-[var(--nhai-border)] rounded-lg px-3 py-2 mb-2 bg-[var(--nhai-bg)]">' +
          '<input type="password" placeholder="Mật khẩu" class="w-full border-2 border-[var(--nhai-border)] rounded-lg px-3 py-2 mb-3 bg-[var(--nhai-bg)]">' +
          '<button type="button" data-do-login class="btn-main w-full py-2.5">Đăng nhập</button>' +
          '<p class="text-xs text-[var(--nhai-muted)] mt-3">Bằng việc đăng nhập, bạn đồng ý với <a href="terms.html" class="text-[var(--nhai-accent)]">Điều khoản sử dụng</a> và <a href="privacy.html" class="text-[var(--nhai-accent)]">Chính sách quyền riêng tư</a>.</p>' +
        "</div>" +
      "</div>"
    );
    document.body.appendChild(bd);
    bd.addEventListener("click", function (e) {
      if (e.target === bd || e.target.closest("[data-close]")) { closeOverlay(); return; }
      if (e.target.closest("[data-do-login], [data-provider]")) {
        localStorage.setItem("nhai.mockLogin", "1");
        renderLoggedIn();
        closeOverlay();
        NHAI.toast("Đã đăng nhập (bản demo) 👋");
      }
    });
  }
  NHAI.openLogin = openLogin;

  function renderLoggedIn() {
    var btns = document.querySelectorAll("[data-topbar] [data-login], [data-login-mobile]");
    var xp = document.querySelectorAll("[data-user] .text-xs");
    var name = localStorage.getItem("nhai.mockName") || "T";
    var initials = name.trim().slice(0, 2).toUpperCase();
    btns.forEach(function (btn) {
      btn.textContent = initials;
      btn.classList.remove("btn-main");
      btn.classList.add("btn-ghost", "rounded-full", "w-9", "h-9", "flex", "items-center", "justify-center", "font-bold");
      btn.title = "Đăng xuất (demo) — " + name;
    });
    btns.forEach(function (btn) {
      btn.removeEventListener("click", openLogin);
      btn.addEventListener("click", function () {
        localStorage.removeItem("nhai.mockLogin");
        location.reload();
      });
    });
    var xpVal = 0;
    try { xpVal = parseInt(localStorage.getItem("nhai.xp"), 10) || 0; } catch (e) { /* silent */ }
    xp.forEach(function (el) { el.textContent = "⚡ " + xpVal + " — mỗi câu trả lời đúng +1"; });
  }

  /* ---------- settings panel ---------- */
  function toggleSettings() {
    var existing = document.querySelector("[data-overlay]");
    if (existing && existing.getAttribute("data-kind") === "settings") { closeOverlay(); return; }
    closeOverlay();
    var theme = localStorage.getItem("nhai.theme") || "light";
    var voice = localStorage.getItem("nhai.voice") || "female";
    var bubble = localStorage.getItem("nhai.chatBubble") !== "0";
    var sel = localStorage.getItem("nhai.selectionLookup") !== "0";
    var on = function (v) { return v ? "btn-main" : "btn-ghost"; };
    var bd = NHAI.el(
      '<div class="modal-backdrop" data-overlay data-kind="settings">' +
        '<div class="card shadow-neo w-full max-w-md p-6 max-h-[85vh] overflow-y-auto">' +
          '<div class="flex items-center justify-between mb-1"><h2 class="text-2xl font-extrabold">⚙️ Cài đặt</h2>' +
          '<button type="button" data-close class="btn-ghost w-9 h-9">✕</button></div>' +
          '<p class="text-sm text-[var(--nhai-muted)] mb-4">Tùy chỉnh trải nghiệm học của bạn.</p>' +
          '<div class="mb-5"><p class="text-sm font-bold mb-2">Giao diện</p><div class="grid grid-cols-2 gap-2">' +
            '<button type="button" data-theme="light" class="' + on(theme === "light") + ' py-2">☀️ Sáng</button>' +
            '<button type="button" data-theme="dark" class="' + on(theme === "dark") + ' py-2">🌙 Tối</button></div></div>' +
          '<div class="mb-5"><p class="text-sm font-bold mb-2">Giọng đọc tiếng Trung</p><div class="grid grid-cols-2 gap-2">' +
            '<button type="button" data-voice="female" class="' + on(voice === "female") + ' py-2">👩 Nữ</button>' +
            '<button type="button" data-voice="male" class="' + on(voice === "male") + ' py-2">👨 Nam</button></div></div>' +
          '<div class="space-y-2">' +
            '<label class="flex items-center justify-between card p-3 cursor-pointer"><span class="text-sm font-semibold">Bong bóng chat AI</span><input type="checkbox" data-flag="nhai.chatBubble" ' + (bubble ? "checked" : "") + '></label>' +
            '<label class="flex items-center justify-between card p-3 cursor-pointer"><span class="text-sm font-semibold">Tra từ khi bôi đen</span><input type="checkbox" data-flag="nhai.selectionLookup" ' + (sel ? "checked" : "") + '></label>' +
          "</div>" +
        "</div>" +
      "</div>"
    );
    document.body.appendChild(bd);
    bd.addEventListener("click", function (e) {
      if (e.target === bd || e.target.closest("[data-close]")) { closeOverlay(); return; }
      var t = e.target.closest("[data-theme],[data-voice],[data-flag]");
      if (!t) return;
      if (t.dataset.theme) { localStorage.setItem("nhai.theme", t.dataset.theme); applyTheme(); toggleSettings(); }
      if (t.dataset.voice) { localStorage.setItem("nhai.voice", t.dataset.voice); toggleSettings(); }
      if (t.dataset.flag) { localStorage.setItem(t.dataset.flag, t.checked ? "1" : "0"); }
    });
  }
  function applyTheme() { document.documentElement.classList.toggle("dark", localStorage.getItem("nhai.theme") === "dark"); }

  /* ---------- selection lookup ---------- */
  document.addEventListener("mouseup", function () {
    if (localStorage.getItem("nhai.selectionLookup") === "0") return;
    var sel = window.getSelection ? String(window.getSelection()).trim() : "";
    var old = document.querySelector("[data-sel-lookup]");
    if (old) old.remove();
    if (!sel || sel.length > 20) return;
    var r = window.getSelection().getRangeAt(0).getBoundingClientRect();
    var pop = NHAI.el('<div data-sel-lookup class="card shadow-neo fixed z-[2147481000] p-2 text-sm"><a href="dictionary.html?q=' + encodeURIComponent(sel) + '" class="font-semibold text-[var(--nhai-accent)]">Tra “' + sel + '”</a></div>');
    pop.style.left = Math.max(8, r.left + window.scrollX) + "px";
    pop.style.top = (r.bottom + window.scrollY + 6) + "px";
    document.body.appendChild(pop);
  });

  /* ---------- floating widgets ---------- */
  function renderFloating() {
    var host = document.createElement("div");
    host.innerHTML =
      '<div class="fixed right-4 bottom-6 z-[600] flex flex-col items-end gap-2">' +
        '<div data-ai-panel class="hidden card shadow-neo w-80 p-3 mb-1">' +
          '<div class="flex items-center justify-between mb-2"><span class="font-bold text-sm">🤖 Tiểu Ngữ — trợ lý AI của Nhai HSK</span>' +
          '<button type="button" data-ai-close class="btn-ghost w-7 h-7 text-xs">✕</button></div>' +
          '<div data-ai-log class="space-y-2 max-h-64 overflow-y-auto text-sm">' +
            '<div class="bg-[var(--nhai-soft)] rounded-lg p-2">Xin chào! Mình là trợ lý Nhai HSK. Hỏi về pinyin, từ vựng hoặc bấm một bài để học nhé!</div>' +
          "</div>" +
          '<div class="flex gap-2 mt-2"><input data-ai-input class="flex-1 border-2 border-[var(--nhai-border)] rounded-lg px-2 py-1.5 bg-[var(--nhai-bg)]" placeholder="Nhập câu hỏi…">' +
          '<button type="button" data-ai-send class="btn-main px-3">➤</button></div>' +
        "</div>" +
        '<button type="button" data-ai class="card shadow-neo relative w-[90px] h-[58px] hover:-translate-y-0.5 transition-transform">' +
          '<span class="absolute inset-0 flex items-center justify-center text-3xl" aria-hidden="true">🤖</span>' +
          '<span class="absolute bottom-0.5 right-1 text-lg -rotate-12" aria-hidden="true">🍅</span>' +
        "</button>" +
        '<button type="button" data-msg class="btn-ghost px-3 py-2 text-sm">💬 Nhắn tin</button>' +
        '<button type="button" data-donate class="btn-main px-3 py-2 text-sm">❤️ Ủng hộ Nhai HSK</button>' +
      "</div>";
    document.body.appendChild(host);
    if (localStorage.getItem("nhai.chatBubble") === "0") host.querySelector("[data-ai]").style.display = "none";
    host.querySelector("[data-ai]").addEventListener("click", function () {
      host.querySelector("[data-ai-panel]").classList.toggle("hidden");
    });
    host.querySelector("[data-ai-close]").addEventListener("click", function () {
      host.querySelector("[data-ai-panel]").classList.add("hidden");
    });
    var send = function () {
      var inp = host.querySelector("[data-ai-input]");
      var log = host.querySelector("[data-ai-log]");
      if (!inp.value.trim()) return;
      log.appendChild(NHAI.el('<div class="ml-8 bg-[var(--nhai-soft)] rounded-lg p-2">' + inp.value.replace(/</g, "&lt;") + "</div>"));
      inp.value = "";
      setTimeout(function () {
        log.appendChild(NHAI.el('<div class="bg-[var(--nhai-soft)] rounded-lg p-2">Mình là bản demo — thử bấm ⭐ trong bài học, tra từ điển hoặc vào bài từ vựng để học nhé!</div>'));
        log.scrollTop = log.scrollHeight;
      }, 400);
      log.scrollTop = log.scrollHeight;
    };
    host.querySelector("[data-ai-send]").addEventListener("click", send);
    host.querySelector("[data-ai-input]").addEventListener("keydown", function (e) { if (e.key === "Enter") send(); });
    host.querySelector("[data-msg]").addEventListener("click", function () {
      NHAI.toast(NHAI.isLoggedIn() ? "Hộp tin nhắn đang được mở (demo)…" : "Tin nhắn chỉ khả dụng khi đăng nhập");
    });
    host.querySelector("[data-donate]").addEventListener("click", function () { NHAI.toast("Cảm ơn bạn đã ủng hộ Nhai HSK! ❤️"); });
  }

  function closeOverlay() {
    document.querySelectorAll("[data-overlay]").forEach(function (o) { o.remove(); });
  }

  /* ---------- boot ---------- */
  applyTheme();
  if (document.readyState === "complete") boot();
  else document.addEventListener("DOMContentLoaded", boot);
  function boot() {
    renderShell();
    renderFloating();
    if ("speechSynthesis" in window) speechSynthesis.getVoices(); // warm-up
    document.addEventListener("keydown", function (e) {
      if (e.altKey && (e.key === "t" || e.key === "T")) NHAI.toast("Không có thông báo mới");
    });
    document.dispatchEvent(new CustomEvent("nhai:shell-ready"));
  }
})();
